%Set preferences with setdbprefs.
setdbprefs('DataReturnFormat', 'cellarray');
setdbprefs('NullNumberRead', 'NaN');
setdbprefs('NullStringRead', 'null');


%Make connection to database.  Note that the password has been omitted.
%Using ODBC driver.
conn = database('FaceDBConnection', 'root', '');

%Read data from database.
curs = exec(conn, ['SELECT 	suspect.PersonID'...
    ' ,	suspect.PersonName'...
    ' ,	suspect.`D.O.B`'...
    ' ,	suspect.Sex'...
    ' ,	suspect.Height'...
    ' ,	suspect.Weight'...
    ' ,	suspect.EyeColor'...
    ' ,	suspect.Hair'...
    ' ,	suspect.Ethnicity'...
    ' ,	suspect.ContactDetails'...
    ' ,	suspect.Address'...
    ' ,	suspect.Description'...
    ' ,	suspect.Country'...
    ' ,	suspect.`Criminal History`'...
    ' ,	suspect.UniqueClass'...
    ' ,	suspect.FaceImage'...
    ' FROM 	`facerecognitiondb`.suspect ']);

curs = fetch(curs);
close(curs);

%Assign data to output variable
SuspectInfoTable = curs.Data;

%Close database connection.
close(conn);

%Clear variables
clear curs conn